version: '3.8'
services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      # change the host to the Postgres service name
      DATABASE_POSTGRES_HOST: postgres
    command: > 
      sh -cx "npm i -g pm2
      && pm2 start yarn --interpreter bash --name api --watch false -- start:debug
      && pm2 start yarn --interpreter bash --name prisma -- db:studio
      && pm2 logs"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  postgres-data: